// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZv3BMtFC1h5OwJmNUMfWahX3QOFhGA9g',
    appId: '1:310432263667:web:f018e8ed25e3744d387686',
    messagingSenderId: '310432263667',
    projectId: 'bazara-tecnical-test',
    authDomain: 'bazara-tecnical-test.firebaseapp.com',
    storageBucket: 'bazara-tecnical-test.appspot.com',
    measurementId: 'G-034CSQQ62W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJjUxp5hMRh4pB748ZEypfDljBaOz77s',
    appId: '1:310432263667:android:018d782f36e83eaa387686',
    messagingSenderId: '310432263667',
    projectId: 'bazara-tecnical-test',
    storageBucket: 'bazara-tecnical-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRn-dc7BySwhkRjLiCNn8t_TaJIQ2BJtQ',
    appId: '1:310432263667:ios:94a75dce822870a1387686',
    messagingSenderId: '310432263667',
    projectId: 'bazara-tecnical-test',
    storageBucket: 'bazara-tecnical-test.appspot.com',
    iosClientId: '310432263667-vs14ecb43d848mso3endrp1m5nlvg1ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.bazaraTecnicalTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRn-dc7BySwhkRjLiCNn8t_TaJIQ2BJtQ',
    appId: '1:310432263667:ios:94a75dce822870a1387686',
    messagingSenderId: '310432263667',
    projectId: 'bazara-tecnical-test',
    storageBucket: 'bazara-tecnical-test.appspot.com',
    iosClientId: '310432263667-vs14ecb43d848mso3endrp1m5nlvg1ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.bazaraTecnicalTest',
  );
}
